<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Backfill stock_movements.purpose for the rows written before the column
 * existed (2026_08_17_150000). ONE PASS, ONE RULE, EVERYTHING ELSE 'unknown'.
 *
 * THE RULE. A historical row is classified from its `type` and the EXACT
 * shape of its `reference` — and only where that shape is generated by
 * exactly one writer in this codebase, so that type + shape names one
 * intent and nothing else could have written it:
 *
 *   type      reference (exact, anchored)          purpose      writer
 *   -------   ----------------------------------   ----------   ----------------------------------------------
 *   receipt   GRN for PO #<n>                      receipt      GoodsReceiptService (default reference)
 *   issue     SPE #<n>                             consumption  ShiftProductionEntryService::completeBatch, consumption lines
 *   receipt   SPE #<n>                             output       ShiftProductionEntryService::completeBatch, FG receipt
 *   issue     Delivery for SO #<n>                 dispatch     DeliveryService (default reference)
 *   receipt   Tally opening <yyyy-mm-dd>           opening      TallyOpeningStockService (TallyStockSnapshot::movementReference)
 *   receipt   TALLY-RECONCILE-<n>                  reconcile    TallyStockReconcileService::referenceFor
 *   issue     TALLY-RECONCILE-<n>                  reconcile    TallyStockReconcileService::referenceFor
 *
 * "SPE #<n>" has meant exactly this since the first shift-entry commit
 * (84233db, 937943e): the completion's consumption ISSUES and its FG RECEIPT
 * share the reference, told apart by type — the same fact
 * ShiftProductionEntryService::reverseCompletionEffects already relies on.
 *
 * WHAT IS LEFT 'unknown', DELIBERATELY:
 *   - "SPE #<n> amended", "QC #<n>", "QC #<n> returned" — reversals and
 *     quality moves. A reversal receipt of resin is a consumption undone; a
 *     QC issue of bottles is output undone and a QC receipt is scrap in. None
 *     of those is one purpose in this enum without a judgment call, and a
 *     backfill does not make judgment calls.
 *   - "WO #", "RWO #", "SCO #", "MWO #", "Rejections Out …" — work-order,
 *     rework, subcontract, maintenance and inspection moves: no purpose is
 *     named for them yet, and their writers still say nothing.
 *   - a GRN or delivery whose user TYPED a reference (the service uses the
 *     default only when none was given): indistinguishable from a manual
 *     receipt/issue form carrying the same text.
 *   - any transfer leg, any null reference, any shape on the wrong type, and
 *     any shape with anything before or after it (" (manual)", trailing
 *     spaces) — the match is anchored on purpose.
 *   - `notes` is NOT consulted: it is free text on every writer.
 *
 * A row that already carries a purpose is not re-decided (a re-run, or a
 * row the service stamped between the column and this pass).
 *
 * Counted per purpose and logged, so the pass is auditable rather than
 * assumed. Chunked, portable (the shapes are matched in PHP, not in a
 * dialect's regex), and reversible: down() takes every purpose back to the
 * null the column arrived with.
 */
return new class extends Migration
{
    private const PATTERNS = [
        // [type, anchored regex, purpose]
        ['receipt', '/^GRN for PO #\d+$/', 'receipt'],
        ['issue', '/^SPE #\d+$/', 'consumption'],
        ['receipt', '/^SPE #\d+$/', 'output'],
        ['issue', '/^Delivery for SO #\d+$/', 'dispatch'],
        ['receipt', '/^Tally opening \d{4}-\d{2}-\d{2}$/', 'opening'],
        ['receipt', '/^TALLY-RECONCILE-\d+$/', 'reconcile'],
        ['issue', '/^TALLY-RECONCILE-\d+$/', 'reconcile'],
    ];

    public function up(): void
    {
        // Every purpose the rule can produce is listed even when it counted
        // nothing — a log line that says "opening=0" is a fact; one that
        // omits it is a question.
        $counts = array_fill_keys(['receipt', 'consumption', 'output', 'dispatch', 'opening', 'reconcile', 'unknown', 'already set'], 0);

        DB::table('stock_movements')
            ->select(['id', 'type', 'reference', 'purpose'])
            ->orderBy('id')
            ->chunkById(500, function ($rows) use (&$counts): void {
                $byPurpose = [];

                foreach ($rows as $row) {
                    if ($row->purpose !== null && $row->purpose !== '') {
                        $counts['already set']++;

                        continue;
                    }

                    $purpose = $this->classify((string) $row->type, $row->reference);
                    $byPurpose[$purpose][] = $row->id;
                    $counts[$purpose]++;
                }

                foreach ($byPurpose as $purpose => $ids) {
                    DB::table('stock_movements')->whereIn('id', $ids)->update(['purpose' => $purpose]);
                }
            });

        Log::info(sprintf(
            'stock_movements.purpose backfill: %s',
            collect($counts)->map(fn (int $n, string $purpose) => "{$purpose}={$n}")->implode(', '),
        ));
    }

    /** The rule, applied to one row. */
    private function classify(string $type, ?string $reference): string
    {
        if ($reference === null) {
            return 'unknown';
        }

        foreach (self::PATTERNS as [$patternType, $regex, $purpose]) {
            if ($type === $patternType && preg_match($regex, $reference) === 1) {
                return $purpose;
            }
        }

        return 'unknown';
    }

    public function down(): void
    {
        DB::table('stock_movements')->whereNotNull('purpose')->update(['purpose' => null]);
    }
};
